version: "2"
services:
  lgtmoon-app:
    image: lgtmoon:latest
    container_name: lgtmoon
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials
      - .:/lgtmoon
    ports:
      - 9000:9000
    environment:
      JDBC_DATABASE_URL: "jdbc:postgresql://postgres/lgtmoon"
  postgres:
    image: postgres:10.15
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lgtmoon
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: postgres
